name: Swift

on:
  push:
    branches: [ master, ci-swift ]
  pull_request:
    branches: [ master, ci-swift ]

defaults:
  run:
    working-directory: swift/Diffuser

jobs:
  build:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2

    - name: Generate Project
      run: swift package generate-xcodeproj

    - name: Run Tests on an iPhone
      run: xcodebuild test -destination 'name=iPhone 11' -scheme 'Diffuser-Package'

