name: Swift

on:
  push:
    branches: [ master, ci-swift ]
  pull_request:
    branches: [ master, ci-swift ]

jobs:
  build:
    runs-on: macos-latest

    env:
      working-directory: ./swift/Diffuser

    steps:

    - name: Generate Project
      run: swift package generate-xcodeproj

    - name: Run Tests on an iPhone
      run: xcodebuild test -destination 'name=iPhone 11' -scheme 'Diffuser-Package'
